### ISSUE TITLE
Some doubts about the paper

### ISSUE THREAD

**Issue by TonyXuQAQ** [tansor/VecRoad#10]
Recently I read your paper VecRoad. It is a good job and quite inspiring. But I have some questions about the proposed method and hope you can give me some hints:

1. In 3.2. Iterative Exploration, you added the Trajectory Exploration in VecRoad, and it seems that this is critical for satisfactory performance based on ablation studies. However, the explanation is too concise, and I do not understand the connection between your training strategy and experience replay. From my perspective, you generate multiple predictions instead of one in each step. Why does this work? How could this strategy relieve the drift problem in trajectory prediction tasks? And why is this related to experience replay, which is a commonly used RL strategy?

2. May I know the overall training time of VecRoad in your task? Considering that the iterative decision-making process is always with high time consumption.

3. Do you have any plans to release your training code in the future? Or it cannot be published at all?

Thanks for your patience and really appreciate it if you could offer me any help.

**Comment by tansor** [comment]
Hi, TonyXuQAQ,
1. From the perspective of experience, making multiple chainlike decisions is more consistent than making single decision every time without priori knowledge. For now, we only prove the guess in the perspective of experiments.
2. 1day
3. Due to certain restrictions, the training script cannot be released at this time.
